# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

#labname
labname1: 空间智能通信实验室
labname2: 智能多媒体实验室
# Title of the Site
title: My Test
# Description of the Site
description: A customizable Jekyll portfolio theme
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://www.nxu.edu.cn/images/banner-fj.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: thedevslot@gmail.com
facebook_username: thedevslot
twitter_username: thedevslot
instagram_username: thedevslot
linkedin_username: thedevslot
github_username:  thedevslot
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
tutor1-name: 孙学宏
# URL for the Image of the Author
tutor1-image: /assets/images/sun.jpg
# 60 Words About the Author
tutor1-about: 孙学宏，男，教授，博士，硕士研究生导师。1999年7月毕业于宁夏大学物理电气信息学院通信工程专业；2008年6月获宁夏大学物理电气信息学院电路与系统专业工学硕士学位；2016年7月获北京邮电大学信息与通信工程学院通信与信息系统专业工学博士学位，工作至今。
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
tutor1-url: https://xxgc.nxu.edu.cn/info/1013/2229.htm

# Name of the Author
tutor2-name: 刘丽萍
# URL for the Image of the Author
tutor2-image: /assets/images/liu.jpg
# 60 Words About the Author
tutor2-about: 刘丽萍，女，教授，硕士，硕士研究生导师。2001年11月获西安交通大学电气工程专业工程硕士学位；1993年7月毕业于宁夏工学院工业电气自动化专业，工作至今。
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
tutor2-url: https://phys.nxu.edu.cn/info/1051/1375.htm

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
